---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
      borderless: true
    - direction: Vertical
      body: true
    - direction: Vertical
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
      borderless: true

tabs:
- name: dev
  direction: Vertical
  parts:
  - direction: Vertical
    split_size:
      Percent: 65
  - direction: Vertical
    split_size:
      Percent: 35
- name: docs
  direction: Vertical
- name: git
  direction: Vertical
  parts:
   - direction: Vertical
     run:
       command: {cmd: gitui}
- name: other
  direction: Vertical
