#!/bin/bash

alias be='bundle exec'
alias bec='bundle exec cucumber'
alias bi='bundle install'
alias c='cd ~/code'
alias d='docker'
alias dc='docker-compose'
alias de='docker exec -it'
alias deploy-to-heroku='git push heroku master && heroku run rake db:migrate'
alias reload-dotfiles='source ~/dotfiles/bash/.bashrc'
alias start-docker="bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'"
alias v='vagrant'
alias vd='vagrant destroy'
alias vu='vagrant up'
alias w='cd ~/workspace'

case $(uname) in
  Linux)  alias subl='/usr/bin/subl -a' ;;
  Darwin) alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -a' ;;
esac
