#!/bin/bash

alias be='bundle exec'
alias bec='bundle exec cucumber'
alias c='cd ~/code'
alias w='cd ~/workspace'
alias v='vagrant'
alias vd='vagrant destroy'
alias vu='vagrant up'
alias dc='docker-compose'
alias d='docker'
alias start-docker="bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'"
alias reload-dotfiles='source ~/dotfiles/bash/.bashrc'

case $(uname) in
  Linux)  alias subl='/usr/bin/subl' ;;
  Darwin) alias subl='open -a "Sublime Text"' ;;
esac
