#!/bin/bash

function mk() {
  mkdir -p "$@" && cd "$@"
}

function code () { 
	VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; 
}

function generate_password() {
  openssl rand -base64 $1
}