#!/bin/bash

function mk() {
  mkdir -p "$@" && cd "$@"
}

function code () { 
	VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; 
}

function generate_password() {
  openssl rand -base64 $1
}

function ssh_mount() {
	mkdir -p $2
	case $(uname) in
	  Linux)  
			sshfs $1 $2 -o auto_cache
			;;
	  Darwin) 
			sshfs $1 $2 -o auto_cache,defer_permissions,noappledouble
			;;
	esac
}