#!/bin/bash

. ~/dotfiles/git/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=0
GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_DESCRIBE_STYLE="branch"
GIT_PS1_SHOWUPSTREAM="auto git"

export PROMPT_COMMAND=__prompt_command  # Func to gen PS1 after CMDs

function __prompt_command() {
    local EXIT="$?"             # This needs to be first
    PS1="\n"

    local RCol='\[\e[0m\]'

    local Red='\[\e[0;31m\]'
    local Gre='\[\e[0;32m\]'
    local BYel='\[\e[1;33m\]'
    
    if [ $EXIT != 0 ]; then
        PS1+="${Red}Error Code: ${EXIT}${RCol}\n\n\n"      # Add red if exit code non 0
    fi

    PS1+="${Gre}\u@${BYel}\H: ${RCol}\w$(__git_ps1) \n${RCol}$ ${RCol}"
}
