#!/bin/bash

export LC_ALL=pt_BR.UTF-8
export LC_CTYPE=pt_BR.UTF-8
export LANG=pt_BR.UTF-8

# git editor
export EDITOR="subl -w"

# Always enable colored `grep` output.
export GREP_OPTIONS='--color=auto'
