#!/bin/bash

export LC_ALL=pt_BR.UTF-8
export LC_CTYPE=pt_BR.UTF-8
export LANG=pt_BR.UTF-8

# git editor
export EDITOR="subl -w"

PATH=$PATH:$BASH_DIR/generators/
export PATH

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi